project:
  type: website

website:
  title: "Catbird Analytics"
  navbar:
    background: "#333"
    left: 
      - text: "Home"
        file: index.qmd
      - portfolio.qmd
      - about.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/johnyuill/
      - icon: github
        href: https://github.com/jyuill
      - icon: twitter
        href: https://twitter.com/johnyuill
  open-graph: true
  google-analytics: "G-5XF0SHH0KW"
  cookie-consent: true
format:
  html:
    theme: 
    - spacelab
    - custom-style.scss
    css: styles.css
    include-after-body: "footer.html"
editor: visual

