project:
  type: website

website:
  title: "Catbird Analytics"
  navbar:
    background: "#0B2B75" # Dark Blue 14213D
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Data Products"
        menu:
          - text: "BC Liquor Market Dashboard"
            file: products/bc-lmr-dashboard.qmd
          - text: "Savings Burndown Simulator"
            file: products/savings-burndown-sim.qmd
          - text: "Stock Market Comparisons"
            file: products/stock-market-comparisons.qmd
          - text: "More to Come"
            file: portfolio.qmd
      - portfolio.qmd
      - text: "Tech Blog"
        file: tech-blog.qmd
      - about.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/johnyuill/
      - icon: github
        href: https://github.com/jyuill
      - icon: twitter
        href: https://twitter.com/johnyuill
  open-graph: true
  google-analytics: "G-5XF0SHH0KW"
  cookie-consent: true
format:
  html:
    theme: 
    - spacelab
    - custom-style.scss
    css: styles.css
    include-after-body: "footer.html"
editor: visual

